### ISSUE TITLE
Add a license to this code

### ISSUE THREAD

**Issue by sam-lord** [Doist/react-interpolate#21]
Please could you add an open source license to this code?

I'm guessing it's meant to be open source, but without any license file or entry in package.json it's hard to tell the intention.

**Comment by sam-lord** [comment]
@deorus @miottid Just tagging you in case this is an easy / quick thing to do.

**Comment by henningmu** [comment]
@sam-lord thank you for bringing this to our attention. This project was meant to be licensed under MIT and I have now added the license to the repo and flagged it as such in the package.json 👍
